Multi/urls.py
from django.contrib import admin
from django.urls import path
from mainApp import views
from mainApp.views import GigDetails, CartView, OrderCheckoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.get_home_page, name="get_home_page"),
    path('gigs_details/<int:id>', GigDetails.as_view(), name="gig_details"),
    path('cart/', CartView.as_view(), name="CartView"),
    path('checkout/', OrderCheckoutView.as_view(), name="OrderCheckoutView"),
    # path('cart/', views.get_checkout_page, name="get_checkout_page"),
    path('post/', views.post, name="post"),
    
    # path('add_basic/', views.add_basic_package, name="add_basic_package"),
]

mainApp/models.py
from django.db import models
from django.contrib.auth.models import User


class Seller(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=120)
    phone_number = models.CharField(max_length=120)


def __str__(self):
    return self.full_name



class Package(models.Model):
    title = models.CharField(max_length=210)

    def __str__(self):
        return self.title


class Gig(models.Model):
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE, null=True)
    gig_title = models.CharField(max_length=520)
    packages = models.ManyToManyField(Package, through='GigManager')

    def __str__(self):
        return self.gig_title

    @staticmethod
    def get_gig_ids(ids):
        return Gig.objects.filter(id__in=ids)



class GigManager(models.Model):
    gig = models.ForeignKey(Gig, on_delete=models.CASCADE, null=True)
    package = models.ForeignKey(Package, on_delete=models.CASCADE, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    @staticmethod
    def get_gig(ids):
        return GigManager.objects.filter(id__in=ids)



class Order(models.Model):
    # Buyer
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=120)
    package = models.ForeignKey(GigManager, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00, null=True)
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    is_paid = models.BooleanField(default=False, null=True)



    def __str__(self):
        return self.name


    def save(self, *args, **kwargs):
        self.total = self.price
        super().save(*args, **kwargs)

mainApp/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Gig, GigManager, Order
from django.views import View

def get_home_page(request):
    
    gigs = Gig.objects.all().order_by('-id')
    
    print(gigs)
    
    args = {
        'gigs': gigs
    }
    return render(request, 'index.html', args)


      
class GigDetails(View):
    def get(self, request, id):
        gig_details = Gig.objects.get(pk=id)
        
        cart = request.session.get('cart')
        
        if not cart:
            request.session['cart'] = {}
    
        args = {
        'gig_details': gig_details     
        }
        return render(self.request, 'gig_details.html', args)
    
def post(request):
    cart = request.session.get('cart', {})
    print(cart)
    package_id = request.POST.get('package_id')
    remove = request.POST.get('remove')
        
    if cart:
        quantity = cart.get(package_id)
        if quantity:
            cart[package_id] = quantity + 1
        else:
            cart[package_id] = 1
    else:
        cart = {}
        cart[package_id] = 1
        
    request.session['cart'] = cart
        
    print('CART:', request.session['cart'])
        
    return redirect('CartView')
        
        
class CartView(View):
    def get(self, request):
        cart = request.session.get('cart')
        if not cart:
            request.session['cart'] = {}
        ids = list(request.session.get('cart').keys())
        cart_products = GigManager.get_gig(ids)
        print(cart)
        context = {
            'cart_products': cart_products
        }
        return render(self.request, 'cart.html', context)



class OrderCheckoutView(View):
    def get(self, request):
        cart = request.session.get('cart')
        if not cart:
            request.session['cart'] = {}
        ids = list(request.session.get('cart').keys())
        cart_products = GigManager.get_gig(ids)
        print(cart)
        context = {
            'cart_products': cart_products
        }
        return render(self.request, 'checkout.html', context)


    def post(self, request):
        cart = request.session.get('cart')
        name = request.POST.get('name')

        packages = GigManager.get_gig(list(cart.keys()))
        user = request.user
        
        for package in packages:

            order = Order(
                    name = name,
                    user = user,
                    package = package,
                    price = package.price,
                    seller = package.gig.seller
                )
            print(package)
            print(order)

            order.save()
            request.session['cart'] = {}

            return HttpResponse("Order Has Been Placed!")

mainApp/templates/base.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

<style>
	body{
		background: #f5f5f5;
	}
</style>

mainApp/templates/cart.html
{% load custom_filter %}
{% include 'base.html' %}
<div class="container p-5">
Cart Page 
</div>

<div class="container p-5">

<table class="table p-5 bg-light">
    <tr>
        <th>Package</th>
        <th>QUANTITY</th>
        <th>PRICE</th>
    </tr>

{% for c in cart_products %}
<tr>
    <td>{{c.package}}</td>
    <td><p class="badge bg-dark">{{ c|cart_quantity:request.session.cart }}</p></td>
    <td>${{ c.price }}</td>
    
</tr>        
{% endfor %}
</table>
<a href="{% url 'OrderCheckoutView' %}" class="btn btn-primary">Go To Checkout</a>
</div>

mainApp/templates/checkout.html
{% include 'base.html' %}
{% load custom_filter %}

<div class="container bg-light p-5 m-5">
	<ul>	
		{% for c in cart_products %}
			<li>{{c.package}}</li>
			<p class="badge bg-dark">{{ c|cart_quantity:request.session.cart }}</p>
			<hr>
		{% endfor %}
	</ul>
</div>


<br><br>

<div class="container p-5" style="background: #fff;">
	<form action="" method="POST" class="form">
		{% csrf_token %}
			<label>Name</label><br>
			<input type="text" placeholder="Enter your name..." class="form-control" name="name"><br>
			<button type="submit" class="btn btn-primary w-100">ORDER NOW</button>
	</form>
</div>

mainApp/templates/gig_details.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

<hr>
<div class="container bg-light">
    {{ gig_details.gig_title }}

    {% for manager in gig_details.gigmanager_set.all %}
        <form action="{% url 'post' %}" method="POST">
            {% csrf_token %}

            <input type="text" name="package_id" value="{{ manager.id }}">

            <h3>{{ manager.package }}</h3>
            <p>$ {{ manager.price }}</p>

            <input type="submit" value="Add to Cart" class="btn btn-success">
        </form>
    {% endfor %}
</div>

mainApp/templates/index.html
{%  load custom_filter%}
<!DOCTYPE html>
<html>
    <title>Django Multi Order</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

    <body>
        <h3 class="m-4">All Gigs</h3>
        <div class="container">
            {% for g in gigs %}
                {{ g }}
                <p>Starting with ${{ g.gigmanager_set.all|gig_price_start }}</p>
                <a href="{% url 'gig_details' g.id %}" class="btn btn-primary">View Details</a>
            {% endfor %}
        </div>
    </body>
</html>